import Foundation

enum ValleyTables {

    // MARK: - 12 Grape Varieties

    static let varieties: [GrapeVariety] = [
        GrapeVariety(id: "v_aurelan_noir", name: "Aurelan Noir",
                     baseline: TasteProfile(body: 64, tannin: 60, acidity: 50, aroma: 58),
                     aromaFamily: .blackFruit, yield: 90, diseaseResistance: 5, coldTolerance: 4,
                     description: "Deep, structured. Prefers heat-retaining stones. Ages exceptionally."),
        GrapeVariety(id: "v_petrov_blanc", name: "Petrov Blanc",
                     baseline: TasteProfile(body: 36, tannin: 8, acidity: 70, aroma: 64),
                     aromaFamily: .citrus, yield: 110, diseaseResistance: 6, coldTolerance: 8,
                     description: "Crisp white with bright acidity and lemon-pith finish."),
        GrapeVariety(id: "v_lambruvinia", name: "Lambruvinia",
                     baseline: TasteProfile(body: 52, tannin: 42, acidity: 64, aroma: 50),
                     aromaFamily: .redFruit, yield: 105, diseaseResistance: 7, coldTolerance: 6,
                     description: "Lively cherry-toned red, friendly across many terroirs."),
        GrapeVariety(id: "v_helvar_sauvage", name: "Helvar Sauvage",
                     baseline: TasteProfile(body: 44, tannin: 12, acidity: 76, aroma: 78),
                     aromaFamily: .herbal, yield: 95, diseaseResistance: 4, coldTolerance: 7,
                     description: "Pungent, herbaceous, signature green-pepper undertone."),
        GrapeVariety(id: "v_tasselino", name: "Tasselino",
                     baseline: TasteProfile(body: 60, tannin: 52, acidity: 54, aroma: 60),
                     aromaFamily: .spice, yield: 90, diseaseResistance: 5, coldTolerance: 5,
                     description: "Old-vine personality, peppery spice when picked late."),
        GrapeVariety(id: "v_volkrein_riesling", name: "Volkrein Riesling",
                     baseline: TasteProfile(body: 32, tannin: 4, acidity: 82, aroma: 72),
                     aromaFamily: .stone, yield: 100, diseaseResistance: 6, coldTolerance: 10,
                     description: "Mountain-loving aromatic white, petrol depth with age."),
        GrapeVariety(id: "v_mistralia", name: "Mistralia",
                     baseline: TasteProfile(body: 56, tannin: 46, acidity: 58, aroma: 56),
                     aromaFamily: .floral, yield: 95, diseaseResistance: 5, coldTolerance: 5,
                     description: "Floral mid-weight red, lifts beautifully in cooler vintages."),
        GrapeVariety(id: "v_carmene_carrare", name: "Carmene Carrare",
                     baseline: TasteProfile(body: 70, tannin: 64, acidity: 46, aroma: 54),
                     aromaFamily: .earth, yield: 80, diseaseResistance: 4, coldTolerance: 3,
                     description: "Bold, brooding, mushroom-and-leather profile when aged."),
        GrapeVariety(id: "v_black_tipple", name: "Black Tipple",
                     baseline: TasteProfile(body: 72, tannin: 68, acidity: 42, aroma: 50),
                     aromaFamily: .blackFruit, yield: 75, diseaseResistance: 6, coldTolerance: 4,
                     description: "Inky and dense. Needs gentle pressing or it turns harsh."),
        GrapeVariety(id: "v_fioretta", name: "Fioretta",
                     baseline: TasteProfile(body: 50, tannin: 36, acidity: 60, aroma: 64),
                     aromaFamily: .redFruit, yield: 100, diseaseResistance: 6, coldTolerance: 6,
                     description: "Garnacha-style. Sun-loving, generous strawberry top notes."),
        GrapeVariety(id: "v_velrune", name: "Velrune",
                     baseline: TasteProfile(body: 40, tannin: 28, acidity: 68, aroma: 74),
                     aromaFamily: .redFruit, yield: 78, diseaseResistance: 3, coldTolerance: 8,
                     description: "Delicate, perfumed Pinot-style. Rewards patience and clay."),
        GrapeVariety(id: "v_trebbio", name: "Trebbio Bianco",
                     baseline: TasteProfile(body: 38, tannin: 6, acidity: 72, aroma: 56),
                     aromaFamily: .citrus, yield: 120, diseaseResistance: 7, coldTolerance: 6,
                     description: "High-yield workhorse white; clean, lemony, dependable.")
    ]

    static func variety(_ id: String) -> GrapeVariety {
        varieties.first(where: { $0.id == id }) ?? varieties[0]
    }

    // MARK: - 5 Terroir Regions

    static let terroirs: [Terroir] = [
        Terroir(id: "t_limestone", name: "Limestone Hillside",
                modifier: TasteProfile(body: -2, tannin: -2, acidity: 8, aroma: 6),
                yieldFactor: 0.95,
                blurb: "Chalky soils, southern exposure. Acidity races in like a cold creek."),
        Terroir(id: "t_clay_bench", name: "Clay River Bench",
                modifier: TasteProfile(body: 8, tannin: 6, acidity: -4, aroma: 0),
                yieldFactor: 1.05,
                blurb: "Heavy water-holding clay. Plump, fleshy fruit; longer hang times."),
        Terroir(id: "t_volcanic", name: "Volcanic Plateau",
                modifier: TasteProfile(body: 4, tannin: 4, acidity: 4, aroma: 8),
                yieldFactor: 0.9,
                blurb: "Dark mineral soils. Smoky, complex, slow-ripening sites."),
        Terroir(id: "t_schist", name: "Schist Cliffs",
                modifier: TasteProfile(body: 6, tannin: 8, acidity: 2, aroma: 6),
                yieldFactor: 0.85,
                blurb: "Heat-radiating broken stone. Demands courage and patient pruning."),
        Terroir(id: "t_alluvial", name: "Alluvial Lowland",
                modifier: TasteProfile(body: -4, tannin: -2, acidity: -2, aroma: -2),
                yieldFactor: 1.15,
                blurb: "Fertile river plain. Forgiving, abundant; never sublime alone.")
    ]

    static func terroir(_ id: String) -> Terroir {
        terroirs.first(where: { $0.id == id }) ?? terroirs[0]
    }

    // MARK: - 8 Barrel Types

    static let barrelTypes: [BarrelType] = [
        BarrelType(id: "bt_light_oak", name: "Light Oak",
                   monthlyModifier: TasteProfile(body: 0.6, tannin: 0.4, acidity: -0.1, aroma: 0.5),
                   purchaseCost: 0,
                   blurb: "Subtle, second-fill oak. A flexible everyday barrel."),
        BarrelType(id: "bt_heavy_french", name: "Heavy Oak French",
                   monthlyModifier: TasteProfile(body: 1.0, tannin: 0.9, acidity: -0.2, aroma: 0.8),
                   purchaseCost: 800,
                   blurb: "Forest-tight French grain. Toasted, refined, generous."),
        BarrelType(id: "bt_heavy_american", name: "Heavy Oak American",
                   monthlyModifier: TasteProfile(body: 1.2, tannin: 0.8, acidity: -0.3, aroma: 0.6),
                   purchaseCost: 700,
                   blurb: "Vanilla-coconut sweetness. A loud, confident barrel."),
        BarrelType(id: "bt_acacia", name: "Acacia",
                   monthlyModifier: TasteProfile(body: 0.4, tannin: 0.2, acidity: 0.2, aroma: 1.0),
                   purchaseCost: 600,
                   blurb: "Floral lift, classic for fragrant whites."),
        BarrelType(id: "bt_chestnut", name: "Chestnut",
                   monthlyModifier: TasteProfile(body: 0.8, tannin: 0.6, acidity: 0.1, aroma: 0.3),
                   purchaseCost: 500,
                   blurb: "Rustic depth, mahogany hue. The cellar-master's secret."),
        BarrelType(id: "bt_stainless", name: "Stainless Steel",
                   monthlyModifier: TasteProfile(body: 0.0, tannin: -0.1, acidity: 0.4, aroma: -0.2),
                   purchaseCost: 0,
                   blurb: "Preserves purity. No oxygen ingress, sharp clarity."),
        BarrelType(id: "bt_concrete", name: "Concrete Egg",
                   monthlyModifier: TasteProfile(body: 0.3, tannin: 0.1, acidity: 0.3, aroma: 0.4),
                   purchaseCost: 1200,
                   blurb: "Silken texture from convection. Neutral, slow, mysterious."),
        BarrelType(id: "bt_amphora", name: "Amphora",
                   monthlyModifier: TasteProfile(body: 0.2, tannin: 0.5, acidity: 0.2, aroma: 0.9),
                   purchaseCost: 1400,
                   blurb: "Clay vessel; orange-wine traditions and earthy aromatics.")
    ]

    static func barrelType(_ id: String) -> BarrelType {
        barrelTypes.first(where: { $0.id == id }) ?? barrelTypes[0]
    }

    // MARK: - 60 Buyer Archetypes

    static let buyers: [BuyerArchetype] = {
        func p(_ b: Double, _ t: Double, _ a: Double, _ r: Double) -> TasteProfile {
            TasteProfile(body: b, tannin: t, acidity: a, aroma: r)
        }
        return [
            BuyerArchetype(id: "b_royal_somm", name: "Royal Sommelier",
                           preference: p(70, 60, 60, 70), minAgeMonths: 24, maxAgeMonths: 120,
                           basePrice: 80, blurb: "Court-trained palate. Pays handsomely for harmony."),
            BuyerArchetype(id: "b_cathedral", name: "Cathedral Cellar",
                           preference: p(60, 30, 60, 55), minAgeMonths: 18, maxAgeMonths: 96,
                           basePrice: 60, blurb: "Holy festivals demand smooth, dignified pours."),
            BuyerArchetype(id: "b_tavern_mistress", name: "Tavern Mistress",
                           preference: p(45, 30, 55, 35), minAgeMonths: 0, maxAgeMonths: 36,
                           basePrice: 25, blurb: "Volume-friendly, expects punchy wines for the boards."),
            BuyerArchetype(id: "b_wine_critic", name: "Wine Critic",
                           preference: p(60, 65, 70, 80), minAgeMonths: 24, maxAgeMonths: 200,
                           basePrice: 95, blurb: "Brutal pen, lavish purse when impressed."),
            BuyerArchetype(id: "b_festival_master", name: "Festival Master",
                           preference: p(55, 40, 60, 65), minAgeMonths: 6, maxAgeMonths: 60,
                           basePrice: 40, blurb: "Buys for the harvest galas. Loves crowd-pleasers."),
            BuyerArchetype(id: "b_foreign_ambassador", name: "Foreign Ambassador",
                           preference: p(70, 55, 50, 65), minAgeMonths: 12, maxAgeMonths: 84,
                           basePrice: 70, blurb: "Sends crates to a distant capital."),
            BuyerArchetype(id: "b_local_cooperative", name: "Local Cooperative",
                           preference: p(50, 35, 50, 45), minAgeMonths: 0, maxAgeMonths: 24,
                           basePrice: 20, blurb: "Bulk discount, dependable repeat business."),
            BuyerArchetype(id: "b_cooper", name: "Cooper's Guild",
                           preference: p(60, 60, 45, 50), minAgeMonths: 12, maxAgeMonths: 48,
                           basePrice: 45, blurb: "Tasting reference for barrel artisans."),
            BuyerArchetype(id: "b_confectioner", name: "Confectioner",
                           preference: p(60, 30, 40, 70), minAgeMonths: 0, maxAgeMonths: 24,
                           basePrice: 35, blurb: "Sweet-leaning patrons. Pays for aromatics."),
            BuyerArchetype(id: "b_banquet_hall", name: "Banquet Hall",
                           preference: p(55, 45, 55, 55), minAgeMonths: 6, maxAgeMonths: 60,
                           basePrice: 38, blurb: "Royal weddings, ducal birthdays, dynastic toasts."),
            BuyerArchetype(id: "b_spa", name: "Mineral Spa",
                           preference: p(35, 10, 70, 65), minAgeMonths: 0, maxAgeMonths: 36,
                           basePrice: 42, blurb: "Wellness inn. Light, bright, aromatic preferred."),
            BuyerArchetype(id: "b_inn", name: "Crossroads Inn",
                           preference: p(50, 40, 50, 40), minAgeMonths: 0, maxAgeMonths: 30,
                           basePrice: 22, blurb: "Travelers' tap. Buys steadily, sells nightly."),
            BuyerArchetype(id: "b_private_cellar", name: "Private Cellar",
                           preference: p(65, 55, 55, 60), minAgeMonths: 18, maxAgeMonths: 200,
                           basePrice: 75, blurb: "Anonymous collector. Rewards age-worthy bottles."),
            BuyerArchetype(id: "b_religious_order", name: "Religious Order",
                           preference: p(55, 30, 55, 50), minAgeMonths: 12, maxAgeMonths: 72,
                           basePrice: 45, blurb: "Sacraments and contemplative dinners."),
            BuyerArchetype(id: "b_spice_merchant", name: "Spice Merchant",
                           preference: p(60, 45, 55, 80), minAgeMonths: 6, maxAgeMonths: 60,
                           basePrice: 55, blurb: "Aromatic-forward palate, well-traveled tongue."),
            BuyerArchetype(id: "b_apothecary", name: "Royal Apothecary",
                           preference: p(40, 25, 70, 75), minAgeMonths: 0, maxAgeMonths: 36,
                           basePrice: 50, blurb: "Tinctures and tonics. High acidity matters."),
            BuyerArchetype(id: "b_garrison_captain", name: "Garrison Captain",
                           preference: p(55, 50, 45, 35), minAgeMonths: 0, maxAgeMonths: 24,
                           basePrice: 28, blurb: "Rations and reward toasts for soldiers."),
            BuyerArchetype(id: "b_river_trader", name: "River Trader",
                           preference: p(50, 40, 55, 50), minAgeMonths: 6, maxAgeMonths: 48,
                           basePrice: 36, blurb: "Stable cargo for the long barge route."),
            BuyerArchetype(id: "b_caravaner", name: "Desert Caravaner",
                           preference: p(60, 50, 40, 55), minAgeMonths: 12, maxAgeMonths: 72,
                           basePrice: 52, blurb: "Wines that survive the sun and arrive lifted."),
            BuyerArchetype(id: "b_mountain_lodge", name: "Mountain Lodge",
                           preference: p(60, 50, 60, 55), minAgeMonths: 12, maxAgeMonths: 60,
                           basePrice: 44, blurb: "Cold-climate clientele, hearty palates."),
            BuyerArchetype(id: "b_court_chef", name: "Court Chef",
                           preference: p(55, 50, 65, 70), minAgeMonths: 6, maxAgeMonths: 60,
                           basePrice: 60, blurb: "Pairings for the queen's tasting menus."),
            BuyerArchetype(id: "b_dockmaster", name: "Dockmaster",
                           preference: p(50, 45, 50, 40), minAgeMonths: 0, maxAgeMonths: 36,
                           basePrice: 30, blurb: "Tips harbormasters, lubricates contracts."),
            BuyerArchetype(id: "b_historian", name: "Wine Historian",
                           preference: p(60, 60, 55, 65), minAgeMonths: 36, maxAgeMonths: 200,
                           basePrice: 78, blurb: "Buys library bottles and rare vintages."),
            BuyerArchetype(id: "b_painter", name: "Court Painter",
                           preference: p(55, 35, 55, 75), minAgeMonths: 12, maxAgeMonths: 72,
                           basePrice: 56, blurb: "Aromatic obsessive. Studies the bouquet at length."),
            BuyerArchetype(id: "b_master_brewer", name: "Master Brewer",
                           preference: p(50, 50, 60, 50), minAgeMonths: 6, maxAgeMonths: 48,
                           basePrice: 40, blurb: "Crossover client. Studies acid balance closely."),
            BuyerArchetype(id: "b_pilgrim", name: "Pilgrim Lodge",
                           preference: p(45, 30, 55, 45), minAgeMonths: 0, maxAgeMonths: 24,
                           basePrice: 24, blurb: "Modest budgets, weary travelers, large orders."),
            BuyerArchetype(id: "b_apprentice_school", name: "Apprentice School",
                           preference: p(50, 45, 55, 55), minAgeMonths: 6, maxAgeMonths: 48,
                           basePrice: 32, blurb: "Teaching cellar. Wants varietal clarity."),
            BuyerArchetype(id: "b_grand_duke", name: "Grand Duke",
                           preference: p(70, 60, 55, 70), minAgeMonths: 36, maxAgeMonths: 200,
                           basePrice: 110, blurb: "Patronage prize. A single placement makes a year."),
            BuyerArchetype(id: "b_horse_breeder", name: "Horse Breeder",
                           preference: p(60, 55, 50, 45), minAgeMonths: 12, maxAgeMonths: 60,
                           basePrice: 46, blurb: "Stallion banquets, hunter celebrations."),
            BuyerArchetype(id: "b_river_ferry", name: "River Ferry Guild",
                           preference: p(55, 40, 50, 45), minAgeMonths: 0, maxAgeMonths: 30,
                           basePrice: 30, blurb: "Daily passengers, plenty of pours."),
            BuyerArchetype(id: "b_seasonal_fair", name: "Seasonal Fair",
                           preference: p(45, 35, 55, 60), minAgeMonths: 0, maxAgeMonths: 24,
                           basePrice: 28, blurb: "Spring fairground. Quick turnover, eclectic tastes."),
            BuyerArchetype(id: "b_castle_chamberlain", name: "Castle Chamberlain",
                           preference: p(65, 55, 55, 60), minAgeMonths: 24, maxAgeMonths: 96,
                           basePrice: 68, blurb: "Stocking the keep's cellar against winters."),
            BuyerArchetype(id: "b_university", name: "University Refectory",
                           preference: p(50, 40, 60, 55), minAgeMonths: 6, maxAgeMonths: 48,
                           basePrice: 34, blurb: "Faculty dinners. Predictable, repeating orders."),
            BuyerArchetype(id: "b_guild_master", name: "Goldsmith Guild Master",
                           preference: p(65, 55, 50, 65), minAgeMonths: 18, maxAgeMonths: 96,
                           basePrice: 66, blurb: "Status-buyer, wants impression more than precision."),
            BuyerArchetype(id: "b_sea_captain", name: "Sea Captain",
                           preference: p(60, 55, 45, 50), minAgeMonths: 12, maxAgeMonths: 72,
                           basePrice: 48, blurb: "Stable wines for long voyages and storms."),
            BuyerArchetype(id: "b_witchwood_apothecary", name: "Witchwood Apothecary",
                           preference: p(35, 15, 70, 70), minAgeMonths: 0, maxAgeMonths: 24,
                           basePrice: 44, blurb: "Forest-dweller, prefers crisp, fragrant tonics."),
            BuyerArchetype(id: "b_silk_merchant", name: "Silk Merchant",
                           preference: p(60, 45, 55, 75), minAgeMonths: 12, maxAgeMonths: 72,
                           basePrice: 64, blurb: "Aroma-led palate from long eastern trade routes."),
            BuyerArchetype(id: "b_winter_court", name: "Winter Court",
                           preference: p(70, 60, 50, 55), minAgeMonths: 24, maxAgeMonths: 120,
                           basePrice: 82, blurb: "Heavy-bodied, sturdy reds for fireside hours."),
            BuyerArchetype(id: "b_summer_court", name: "Summer Court",
                           preference: p(45, 25, 65, 70), minAgeMonths: 0, maxAgeMonths: 36,
                           basePrice: 58, blurb: "Bright, refreshing, aromatic. The pavilion crowd."),
            BuyerArchetype(id: "b_quarrymaster", name: "Quarrymaster",
                           preference: p(60, 55, 45, 40), minAgeMonths: 6, maxAgeMonths: 48,
                           basePrice: 36, blurb: "Sturdy ration wine for the cut-stone crews."),
            BuyerArchetype(id: "b_traveling_bard", name: "Traveling Bard",
                           preference: p(50, 40, 55, 70), minAgeMonths: 0, maxAgeMonths: 36,
                           basePrice: 30, blurb: "Buys small, tastes broadly, gossips loudly."),
            BuyerArchetype(id: "b_book_collector", name: "Book Collector",
                           preference: p(55, 50, 55, 65), minAgeMonths: 18, maxAgeMonths: 120,
                           basePrice: 58, blurb: "Cellar matches the library: aged and meticulous."),
            BuyerArchetype(id: "b_woodcarver", name: "Woodcarver Guild",
                           preference: p(60, 55, 50, 55), minAgeMonths: 12, maxAgeMonths: 60,
                           basePrice: 42, blurb: "Apprentice celebrations and patron dinners."),
            BuyerArchetype(id: "b_lake_inn", name: "Lake Inn",
                           preference: p(45, 30, 60, 55), minAgeMonths: 0, maxAgeMonths: 36,
                           basePrice: 30, blurb: "Fish-pairing palate, prefers bright whites."),
            BuyerArchetype(id: "b_old_winemaker", name: "Old Winemaker",
                           preference: p(60, 60, 55, 65), minAgeMonths: 24, maxAgeMonths: 200,
                           basePrice: 70, blurb: "Knows everything. Pays only for honesty."),
            BuyerArchetype(id: "b_courier_company", name: "Courier Company",
                           preference: p(55, 45, 55, 50), minAgeMonths: 0, maxAgeMonths: 36,
                           basePrice: 32, blurb: "Riders' rest stops along the post road."),
            BuyerArchetype(id: "b_aviary_keeper", name: "Aviary Keeper",
                           preference: p(40, 25, 65, 70), minAgeMonths: 0, maxAgeMonths: 24,
                           basePrice: 38, blurb: "Royal aviary attendants. Light, fragrant wines."),
            BuyerArchetype(id: "b_tax_collector", name: "Tax Collector",
                           preference: p(60, 50, 55, 55), minAgeMonths: 12, maxAgeMonths: 60,
                           basePrice: 50, blurb: "Hospitality wines for landed magistrates."),
            BuyerArchetype(id: "b_smuggler", name: "Sympathetic Smuggler",
                           preference: p(70, 55, 50, 55), minAgeMonths: 12, maxAgeMonths: 96,
                           basePrice: 72, blurb: "Cash on barrel-head, no questions, no records."),
            BuyerArchetype(id: "b_seasonal_chef", name: "Seasonal Chef",
                           preference: p(50, 40, 60, 65), minAgeMonths: 6, maxAgeMonths: 48,
                           basePrice: 44, blurb: "Tasting-menu obsessive. Loves seasonal expression."),
            BuyerArchetype(id: "b_shipwright", name: "Shipwright Guild",
                           preference: p(60, 55, 45, 45), minAgeMonths: 6, maxAgeMonths: 48,
                           basePrice: 36, blurb: "Robust pours after rigging contracts."),
            BuyerArchetype(id: "b_alchemist", name: "Court Alchemist",
                           preference: p(45, 30, 65, 75), minAgeMonths: 0, maxAgeMonths: 36,
                           basePrice: 52, blurb: "Aromatic studies; insists on bright acidity."),
            BuyerArchetype(id: "b_fisheries_guild", name: "Fisheries Guild",
                           preference: p(40, 20, 70, 60), minAgeMonths: 0, maxAgeMonths: 24,
                           basePrice: 30, blurb: "Brine and bright whites only."),
            BuyerArchetype(id: "b_dairy_estate", name: "Dairy Estate",
                           preference: p(50, 35, 55, 55), minAgeMonths: 0, maxAgeMonths: 24,
                           basePrice: 28, blurb: "Cheese-room pairings, abbeys and abbots."),
            BuyerArchetype(id: "b_temple_steward", name: "Temple Steward",
                           preference: p(55, 35, 55, 55), minAgeMonths: 12, maxAgeMonths: 72,
                           basePrice: 42, blurb: "Saintly festivals and procession nights."),
            BuyerArchetype(id: "b_keep_lord", name: "Keep Lord",
                           preference: p(70, 65, 50, 55), minAgeMonths: 24, maxAgeMonths: 144,
                           basePrice: 84, blurb: "Inherited cellar; replenishes after every campaign."),
            BuyerArchetype(id: "b_seafarer", name: "Seafarer Quartermaster",
                           preference: p(55, 50, 45, 50), minAgeMonths: 6, maxAgeMonths: 60,
                           basePrice: 36, blurb: "Stockpiles for two-year voyages south."),
            BuyerArchetype(id: "b_grain_baron", name: "Grain Baron",
                           preference: p(60, 50, 55, 55), minAgeMonths: 12, maxAgeMonths: 60,
                           basePrice: 52, blurb: "Country estate, bountiful banquets."),
            BuyerArchetype(id: "b_iron_smelter", name: "Iron Smelter Foreman",
                           preference: p(65, 60, 45, 40), minAgeMonths: 6, maxAgeMonths: 48,
                           basePrice: 40, blurb: "Smoky tastes, prefers brawny reds."),
            BuyerArchetype(id: "b_envoy", name: "Diplomatic Envoy",
                           preference: p(60, 50, 55, 65), minAgeMonths: 18, maxAgeMonths: 84,
                           basePrice: 64, blurb: "Wines as treaties: balanced, polished, persuasive.")
        ]
    }()

    static func buyer(_ id: String) -> BuyerArchetype {
        buyers.first(where: { $0.id == id }) ?? buyers[0]
    }

    // MARK: - 30+ Events

    static let events: [GameEvent] = [
        GameEvent(id: "e_phylloxera_scare", name: "Phylloxera Scare",
                  description: "Rumors of root louse in the next valley. The cooperage urges quarantine.",
                  optionA: EventOption(label: "Quarantine vines", coinDelta: -180, prestigeDelta: 1,
                                       cellarDiseaseDelta: -0.05, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Disease pressure drops, payroll rises."),
                  optionB: EventOption(label: "Ignore the rumor", coinDelta: 0, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.18, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Risky. Plots take on creeping infection.")),
        GameEvent(id: "e_mildew", name: "Late Mildew Bloom",
                  description: "Cool wet nights have woken downy mildew across several rows.",
                  optionA: EventOption(label: "Spray copper", coinDelta: -120, prestigeDelta: 0,
                                       cellarDiseaseDelta: -0.1, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Effective, expensive."),
                  optionB: EventOption(label: "Trust the wind", coinDelta: 0, prestigeDelta: -1,
                                       cellarDiseaseDelta: 0.12, yieldShockYears: 1, yieldShockFactor: 0.9,
                                       note: "Some yield will likely suffer.")),
        GameEvent(id: "e_wildfire", name: "Hillside Wildfire",
                  description: "Smoke hangs over the valley. Pickers worry about taint in the skins.",
                  optionA: EventOption(label: "Hire extra crews", coinDelta: -220, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 1, yieldShockFactor: 0.95,
                                       note: "Saves more fruit; bonus to prestige."),
                  optionB: EventOption(label: "Accept smoke taint", coinDelta: 0, prestigeDelta: -1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 1, yieldShockFactor: 0.7,
                                       note: "Yields plunge; reputation slips.")),
        GameEvent(id: "e_royal_commission", name: "Royal Commission",
                  description: "A herald arrives: the Crown requests three bottles of any vintage.",
                  optionA: EventOption(label: "Send your best", coinDelta: 220, prestigeDelta: 3,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Honor and silver."),
                  optionB: EventOption(label: "Decline politely", coinDelta: 0, prestigeDelta: -2,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Rare slight against the Crown.")),
        GameEvent(id: "e_cooperage_shortage", name: "Cooperage Shortage",
                  description: "Heavy oak French barrels are scarce this year. Speculators circle.",
                  optionA: EventOption(label: "Buy at premium", coinDelta: -300, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Stockpile for harder years."),
                  optionB: EventOption(label: "Hold the line", coinDelta: 0, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Refuse the markup.")),
        GameEvent(id: "e_harvest_mutiny", name: "Harvest Hand Mutiny",
                  description: "Pickers demand higher wages on the cusp of optimal pick.",
                  optionA: EventOption(label: "Agree to the raise", coinDelta: -140, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Smooth pick, loyal hands."),
                  optionB: EventOption(label: "Replace with strangers", coinDelta: 0, prestigeDelta: -1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 1, yieldShockFactor: 0.92,
                                       note: "Rough handling; small losses.")),
        GameEvent(id: "e_rival_spy", name: "Rival's Spy",
                  description: "A guest at last week's tasting was no guest at all.",
                  optionA: EventOption(label: "Tighten the cellar", coinDelta: -100, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Hire watchmen, install locks."),
                  optionB: EventOption(label: "Let them feast on rumor", coinDelta: 60, prestigeDelta: -1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Pocket the secret sale; lose face.")),
        GameEvent(id: "e_old_vine_disco", name: "Old Vine Discovery",
                  description: "A neglected plot turns out to hold seventy-year-old vines.",
                  optionA: EventOption(label: "Restore the plot", coinDelta: -200, prestigeDelta: 2,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Future quality boost."),
                  optionB: EventOption(label: "Sell the timber", coinDelta: 160, prestigeDelta: -2,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Quick cash, lasting regret.")),
        GameEvent(id: "e_critic_visit", name: "Wine Critic Visit",
                  description: "A nationally read critic announces a surprise tasting next month.",
                  optionA: EventOption(label: "Polish the cellar", coinDelta: -90, prestigeDelta: 2,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Hire a stagier from the capital."),
                  optionB: EventOption(label: "Show your raw work", coinDelta: 0, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Lean into authenticity.")),
        GameEvent(id: "e_bumper_year", name: "Bumper Year",
                  description: "Nature smiles. The vines hang heavy. Coopers offer surplus barrels.",
                  optionA: EventOption(label: "Expand bottling", coinDelta: -150, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 1, yieldShockFactor: 1.1,
                                       note: "Capitalize on abundance."),
                  optionB: EventOption(label: "Hold inventory", coinDelta: 0, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Steady as it comes.")),
        GameEvent(id: "e_grand_tasting", name: "Grand Tasting Invitation",
                  description: "An invitation to the Capital Grand Tasting arrives in fine ink.",
                  optionA: EventOption(label: "Attend in person", coinDelta: -160, prestigeDelta: 3,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Travel costs; reputation gains."),
                  optionB: EventOption(label: "Send a deputy", coinDelta: -50, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Modest presence, modest gains.")),
        GameEvent(id: "e_blacksmith_son", name: "Blacksmith's Son",
                  description: "A bright apprentice begs you to teach him pruning.",
                  optionA: EventOption(label: "Take him on", coinDelta: -30, prestigeDelta: 1,
                                       cellarDiseaseDelta: -0.02, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "An extra pair of careful hands."),
                  optionB: EventOption(label: "Send him home", coinDelta: 0, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Not your responsibility, alas.")),
        GameEvent(id: "e_river_flood", name: "River Flood",
                  description: "Spring runoff swells the river. The alluvial rows are at risk.",
                  optionA: EventOption(label: "Build temporary dykes", coinDelta: -140, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 1, yieldShockFactor: 0.98,
                                       note: "Mostly saves the harvest."),
                  optionB: EventOption(label: "Accept the loss", coinDelta: 0, prestigeDelta: -1,
                                       cellarDiseaseDelta: 0.06, yieldShockYears: 1, yieldShockFactor: 0.8,
                                       note: "Mud, mildew, and silence.")),
        GameEvent(id: "e_blackbirds", name: "Black Birds",
                  description: "Bird flocks descend on ripening fruit.",
                  optionA: EventOption(label: "Hire watchers", coinDelta: -60, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 1, yieldShockFactor: 1.0,
                                       note: "Steady eyes on the rows."),
                  optionB: EventOption(label: "Trust the nets", coinDelta: 0, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 1, yieldShockFactor: 0.93,
                                       note: "Some losses likely.")),
        GameEvent(id: "e_visiting_master", name: "Visiting Master Valley",
                  description: "A traveling master offers private lessons to your cellar staff.",
                  optionA: EventOption(label: "Pay her fee", coinDelta: -130, prestigeDelta: 2,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Knowledge compounds."),
                  optionB: EventOption(label: "Decline gracefully", coinDelta: 0, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Bow politely, return to work.")),
        GameEvent(id: "e_borrow_press", name: "Neighbor's Broken Press",
                  description: "A neighboring estate's press shatters mid-vintage.",
                  optionA: EventOption(label: "Lend yours for free", coinDelta: 0, prestigeDelta: 2,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Build goodwill."),
                  optionB: EventOption(label: "Charge a steep fee", coinDelta: 120, prestigeDelta: -1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Earn coin, lose neighbors.")),
        GameEvent(id: "e_taxman", name: "The Taxman",
                  description: "The duchy reviews wine duties. A small bribe could ease the audit.",
                  optionA: EventOption(label: "Pay the bribe", coinDelta: -100, prestigeDelta: -1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Quietly handled."),
                  optionB: EventOption(label: "Refuse on principle", coinDelta: -180, prestigeDelta: 2,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Honest, costly, admired.")),
        GameEvent(id: "e_drought_treaty", name: "Drought Water Treaty",
                  description: "Neighboring estates offer to pool water rights against the drought.",
                  optionA: EventOption(label: "Sign the treaty", coinDelta: -80, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 1, yieldShockFactor: 1.05,
                                       note: "Shared irrigation."),
                  optionB: EventOption(label: "Stay independent", coinDelta: 0, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 1, yieldShockFactor: 0.92,
                                       note: "Your wells, your worries.")),
        GameEvent(id: "e_apprentice_steals", name: "Apprentice Pilfers Wine",
                  description: "A junior hand has been sneaking bottles for taverns.",
                  optionA: EventOption(label: "Forgive but fine", coinDelta: 40, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Reputation for justice grows."),
                  optionB: EventOption(label: "Dismiss harshly", coinDelta: 0, prestigeDelta: -1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Other apprentices look uneasy.")),
        GameEvent(id: "e_volcanic_ash", name: "Volcanic Ash Drift",
                  description: "Ash from a distant eruption tints the air at twilight.",
                  optionA: EventOption(label: "Cover the rows", coinDelta: -90, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Protect against fouling."),
                  optionB: EventOption(label: "Embrace the minerality", coinDelta: 0, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "An unusual vintage looms.")),
        GameEvent(id: "e_caravan_offer", name: "Caravan Buyer's Offer",
                  description: "A southern caravan offers gold for ten cases sight unseen.",
                  optionA: EventOption(label: "Accept the deal", coinDelta: 220, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Quick cash, reputation tepid."),
                  optionB: EventOption(label: "Hold for selectors", coinDelta: 0, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Wait for the better customer.")),
        GameEvent(id: "e_steward_dispute", name: "Steward's Dispute",
                  description: "Your steward and head winemaker disagree about pruning policy.",
                  optionA: EventOption(label: "Side with the steward", coinDelta: 0, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.04, yieldShockYears: 1, yieldShockFactor: 1.05,
                                       note: "Pragmatism over precision."),
                  optionB: EventOption(label: "Side with the winemaker", coinDelta: 0, prestigeDelta: 1,
                                       cellarDiseaseDelta: -0.03, yieldShockYears: 1, yieldShockFactor: 0.97,
                                       note: "Precision over abundance.")),
        GameEvent(id: "e_chestnut_grove", name: "Chestnut Grove for Sale",
                  description: "A nearby chestnut grove is auctioned. Could yield rare cooperage.",
                  optionA: EventOption(label: "Acquire the grove", coinDelta: -260, prestigeDelta: 2,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Future chestnut barrels assured."),
                  optionB: EventOption(label: "Bid politely and lose", coinDelta: 0, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Saved coin, lost timber.")),
        GameEvent(id: "e_glass_blower", name: "Glassblower's Trial",
                  description: "A new glassblower offers tinted bottles at half the usual price.",
                  optionA: EventOption(label: "Order a thousand", coinDelta: -110, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Future bottling fees reduced."),
                  optionB: EventOption(label: "Wait for samples", coinDelta: 0, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Cautious craft.")),
        GameEvent(id: "e_label_artist", name: "Label Artist's Petition",
                  description: "A traveling illustrator offers signature label work for shares of profit.",
                  optionA: EventOption(label: "Commission the labels", coinDelta: -80, prestigeDelta: 2,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Bottles look unforgettable."),
                  optionB: EventOption(label: "Stick with the press", coinDelta: 0, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Plain and recognizable.")),
        GameEvent(id: "e_winter_warm", name: "Mild Winter Anomaly",
                  description: "Frost never deepens. Buds risk early break.",
                  optionA: EventOption(label: "Delay budbreak with shading", coinDelta: -120, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 1, yieldShockFactor: 0.98,
                                       note: "Protect the early shoots."),
                  optionB: EventOption(label: "Risk the gamble", coinDelta: 0, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.05, yieldShockYears: 1, yieldShockFactor: 0.88,
                                       note: "A frost could ruin a third of the canes.")),
        GameEvent(id: "e_lost_journal", name: "Lost Cellar Journal",
                  description: "A previous owner's journal surfaces, listing forgotten plot maps.",
                  optionA: EventOption(label: "Buy the journal", coinDelta: -90, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "A blending hint unlocks soon."),
                  optionB: EventOption(label: "Pass on the offer", coinDelta: 0, prestigeDelta: 0,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Anything worth knowing you'll find again.")),
        GameEvent(id: "e_summer_storm", name: "Summer Lightning Storm",
                  description: "A dry thunderstorm splits the air for hours.",
                  optionA: EventOption(label: "Bring crews indoors", coinDelta: -40, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 1, yieldShockFactor: 1.0,
                                       note: "Safety first; some sun lost."),
                  optionB: EventOption(label: "Keep working", coinDelta: 30, prestigeDelta: -1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 1, yieldShockFactor: 0.95,
                                       note: "Risky decision under bright sky.")),
        GameEvent(id: "e_apprentice_brilliant", name: "Brilliant Apprentice",
                  description: "An apprentice proposes a wild new blend.",
                  optionA: EventOption(label: "Bottle a trial cuvee", coinDelta: -50, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Possible new signature."),
                  optionB: EventOption(label: "Cool the enthusiasm", coinDelta: 0, prestigeDelta: -1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Tradition holds.")),
        GameEvent(id: "e_market_panic", name: "Market Panic",
                  description: "A rumor of bad vintage tanks general wine prices.",
                  optionA: EventOption(label: "Slash prices, sell volume", coinDelta: 90, prestigeDelta: -1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Move bottles fast."),
                  optionB: EventOption(label: "Hold inventory tight", coinDelta: 0, prestigeDelta: 1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Wait out the panic.")),
        GameEvent(id: "e_winter_visitor", name: "Winter Visitor",
                  description: "An old friend arrives, asks to taste through your library.",
                  optionA: EventOption(label: "Open the cellar", coinDelta: 0, prestigeDelta: 2,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Word travels with him."),
                  optionB: EventOption(label: "Plead busy season", coinDelta: 0, prestigeDelta: -1,
                                       cellarDiseaseDelta: 0.0, yieldShockYears: 0, yieldShockFactor: 1.0,
                                       note: "Friendship cools."))
    ]

    static func event(_ id: String) -> GameEvent? {
        events.first(where: { $0.id == id })
    }

    // MARK: - 20 Upgrades

    static let upgrades: [Upgrade] = [
        Upgrade(id: "u_more_rows", name: "Expanded Rows", cost: 400,
                blurb: "Reclaim five more planting plots from the eastern slope.",
                category: "Vineyard"),
        Upgrade(id: "u_better_press", name: "Better Press", cost: 600,
                blurb: "Smoother extraction. Press style modifiers reduced in harshness.",
                category: "Cellar"),
        Upgrade(id: "u_oak_supplier", name: "Oak Supplier Contract", cost: 500,
                blurb: "Discounted oak barrel purchases each year.",
                category: "Cellar"),
        Upgrade(id: "u_refrigerated", name: "Refrigerated Cellar", cost: 900,
                blurb: "Aging proceeds more evenly through hot summers.",
                category: "Cellar"),
        Upgrade(id: "u_blending_lab", name: "Blending Laboratory", cost: 700,
                blurb: "Unlocks the experimental blending workspace.",
                category: "Cellar"),
        Upgrade(id: "u_label_printer", name: "Label Press", cost: 350,
                blurb: "Custom labels boost market appeal by a small margin.",
                category: "Sales"),
        Upgrade(id: "u_cooper_shop", name: "Cooper's Shop", cost: 1100,
                blurb: "Maintain and re-toast your own barrels.",
                category: "Cellar"),
        Upgrade(id: "u_scale", name: "Cellar Scale System", cost: 250,
                blurb: "Precise barrel measurements. Improves inventory clarity.",
                category: "Operations"),
        Upgrade(id: "u_fence", name: "Vineyard Fence", cost: 200,
                blurb: "Discourages thieves and deer alike. Yield protection.",
                category: "Vineyard"),
        Upgrade(id: "u_barrel_room_1", name: "Barrel Room Tier I", cost: 600,
                blurb: "Doubles cellar capacity.",
                category: "Cellar"),
        Upgrade(id: "u_barrel_room_2", name: "Barrel Room Tier II", cost: 1100,
                blurb: "Triples cellar capacity. Adds a tasting nook.",
                category: "Cellar"),
        Upgrade(id: "u_barrel_room_3", name: "Barrel Room Tier III", cost: 1700,
                blurb: "Quadruples cellar capacity. Cathedral-like aging halls.",
                category: "Cellar"),
        Upgrade(id: "u_drainage", name: "Drainage Channels", cost: 350,
                blurb: "Wet vintages cause less yield loss.",
                category: "Vineyard"),
        Upgrade(id: "u_irrigation", name: "Drip Irrigation", cost: 500,
                blurb: "Drought vintages cause less yield loss.",
                category: "Vineyard"),
        Upgrade(id: "u_steward", name: "Estate Steward", cost: 850,
                blurb: "Increases negotiation bonus with all buyers by 8%.",
                category: "Operations"),
        Upgrade(id: "u_courier", name: "Courier Service", cost: 400,
                blurb: "Faster order turnover. More market visits per selling season.",
                category: "Sales"),
        Upgrade(id: "u_wine_school", name: "Wine School", cost: 1300,
                blurb: "Unlocks all blending recipe hints in the almanac.",
                category: "Cellar"),
        Upgrade(id: "u_chapel", name: "Estate Chapel", cost: 950,
                blurb: "Religious buyers pay a 15% premium.",
                category: "Sales"),
        Upgrade(id: "u_inn_partnership", name: "Inn Partnership", cost: 650,
                blurb: "Steady taproom buyers visit every season.",
                category: "Sales"),
        Upgrade(id: "u_research_garden", name: "Research Garden", cost: 800,
                blurb: "Improves disease resistance across all plots by 1.",
                category: "Vineyard")
    ]

    static func upgrade(_ id: String) -> Upgrade? {
        upgrades.first(where: { $0.id == id })
    }

    // MARK: - 25 Blending Recipes

    static let recipes: [BlendingRecipe] = [
        BlendingRecipe(id: "r_estate_classic", name: "Estate Classic",
                       target: TasteProfile(body: 55, tannin: 45, acidity: 55, aroma: 60),
                       varietyHints: ["v_aurelan_noir", "v_lambruvinia"],
                       blurb: "A founder's flagship blend: harmonious and approachable."),
        BlendingRecipe(id: "r_river_reserve", name: "River Reserve",
                       target: TasteProfile(body: 60, tannin: 50, acidity: 50, aroma: 55),
                       varietyHints: ["v_carmene_carrare", "v_mistralia"],
                       blurb: "Earthy reserve cuvee shaped by clay-bench fruit."),
        BlendingRecipe(id: "r_summer_cuvee", name: "Summer Cuvee",
                       target: TasteProfile(body: 38, tannin: 12, acidity: 70, aroma: 70),
                       varietyHints: ["v_petrov_blanc", "v_trebbio"],
                       blurb: "Bright, citrus-led white for warm-evening pours."),
        BlendingRecipe(id: "r_mountain_silver", name: "Mountain Silver",
                       target: TasteProfile(body: 34, tannin: 6, acidity: 78, aroma: 70),
                       varietyHints: ["v_volkrein_riesling"],
                       blurb: "Single-variety Riesling-style mineral spike."),
        BlendingRecipe(id: "r_velrune_perfume", name: "Velrune Perfume",
                       target: TasteProfile(body: 42, tannin: 28, acidity: 65, aroma: 72),
                       varietyHints: ["v_velrune"],
                       blurb: "Pinot-style perfumed solo, demands cool-climate vintages."),
        BlendingRecipe(id: "r_volcanic_blackstone", name: "Volcanic Blackstone",
                       target: TasteProfile(body: 68, tannin: 60, acidity: 55, aroma: 65),
                       varietyHints: ["v_black_tipple", "v_tasselino"],
                       blurb: "Dense ash-soil reserve. Coopers love this one."),
        BlendingRecipe(id: "r_orchard_cuvee", name: "Orchard Cuvee",
                       target: TasteProfile(body: 40, tannin: 14, acidity: 60, aroma: 68),
                       varietyHints: ["v_petrov_blanc", "v_volkrein_riesling"],
                       blurb: "Two-grape stone-fruit chorus."),
        BlendingRecipe(id: "r_sunset_rose", name: "Sunset Rose",
                       target: TasteProfile(body: 42, tannin: 22, acidity: 62, aroma: 68),
                       varietyHints: ["v_fioretta", "v_petrov_blanc"],
                       blurb: "Strawberry-driven blush, evening-friendly."),
        BlendingRecipe(id: "r_old_vine_reserve", name: "Old Vine Reserve",
                       target: TasteProfile(body: 64, tannin: 58, acidity: 52, aroma: 60),
                       varietyHints: ["v_tasselino"],
                       blurb: "Single-variety expression of patient pruning."),
        BlendingRecipe(id: "r_court_white", name: "Court White",
                       target: TasteProfile(body: 36, tannin: 8, acidity: 72, aroma: 60),
                       varietyHints: ["v_trebbio"],
                       blurb: "Dependable, presentable, dependable again."),
        BlendingRecipe(id: "r_harvest_red", name: "Harvest Red",
                       target: TasteProfile(body: 50, tannin: 40, acidity: 55, aroma: 50),
                       varietyHints: ["v_lambruvinia"],
                       blurb: "A celebration red sold in the festival kiosks."),
        BlendingRecipe(id: "r_winter_warmer", name: "Winter Warmer",
                       target: TasteProfile(body: 68, tannin: 60, acidity: 48, aroma: 55),
                       varietyHints: ["v_carmene_carrare", "v_black_tipple"],
                       blurb: "Heavy, brooding reserve for the long nights."),
        BlendingRecipe(id: "r_spring_white", name: "Spring White",
                       target: TasteProfile(body: 34, tannin: 6, acidity: 68, aroma: 75),
                       varietyHints: ["v_helvar_sauvage"],
                       blurb: "Crisp herbal entry-level white. Reliable seller."),
        BlendingRecipe(id: "r_grand_cru", name: "Grand Cru",
                       target: TasteProfile(body: 70, tannin: 60, acidity: 58, aroma: 72),
                       varietyHints: ["v_aurelan_noir", "v_velrune", "v_tasselino"],
                       blurb: "The estate's prestige cuvee. Pilgrimage bottle."),
        BlendingRecipe(id: "r_signature_white", name: "Signature White",
                       target: TasteProfile(body: 36, tannin: 6, acidity: 70, aroma: 68),
                       varietyHints: ["v_volkrein_riesling", "v_petrov_blanc"],
                       blurb: "Tasting-flight workhorse. Always sold out."),
        BlendingRecipe(id: "r_volcanic_white", name: "Volcanic White",
                       target: TasteProfile(body: 40, tannin: 10, acidity: 70, aroma: 76),
                       varietyHints: ["v_helvar_sauvage"],
                       blurb: "Smoky white sited on volcanic plateau lots."),
        BlendingRecipe(id: "r_market_red", name: "Market Red",
                       target: TasteProfile(body: 48, tannin: 36, acidity: 56, aroma: 52),
                       varietyHints: ["v_lambruvinia", "v_fioretta"],
                       blurb: "Friendly, weekend-fair red for the kiosks."),
        BlendingRecipe(id: "r_amphora_orange", name: "Amphora Orange",
                       target: TasteProfile(body: 46, tannin: 30, acidity: 62, aroma: 72),
                       varietyHints: ["v_helvar_sauvage", "v_trebbio"],
                       blurb: "Skin-contact white aged in amphora. Cult favorite."),
        BlendingRecipe(id: "r_aged_reserve", name: "Aged Reserve",
                       target: TasteProfile(body: 62, tannin: 55, acidity: 55, aroma: 65),
                       varietyHints: ["v_aurelan_noir"],
                       blurb: "Aged at least three years in oak. Library bottle."),
        BlendingRecipe(id: "r_dawn_cuvee", name: "Dawn Cuvee",
                       target: TasteProfile(body: 38, tannin: 8, acidity: 72, aroma: 62),
                       varietyHints: ["v_petrov_blanc"],
                       blurb: "Breakfast banquet white. Vivid, clean."),
        BlendingRecipe(id: "r_dusk_blend", name: "Dusk Blend",
                       target: TasteProfile(body: 54, tannin: 40, acidity: 55, aroma: 62),
                       varietyHints: ["v_mistralia", "v_fioretta"],
                       blurb: "Floral, sun-tinted red for evening tables."),
        BlendingRecipe(id: "r_cathedral_red", name: "Cathedral Red",
                       target: TasteProfile(body: 58, tannin: 45, acidity: 55, aroma: 60),
                       varietyHints: ["v_carmene_carrare", "v_mistralia"],
                       blurb: "Ceremonial-grade red for processions."),
        BlendingRecipe(id: "r_harbor_white", name: "Harbor White",
                       target: TasteProfile(body: 36, tannin: 6, acidity: 70, aroma: 60),
                       varietyHints: ["v_trebbio", "v_petrov_blanc"],
                       blurb: "Sailor's pour, salt-tinged and bright."),
        BlendingRecipe(id: "r_alchemy_cuvee", name: "Alchemy Cuvee",
                       target: TasteProfile(body: 52, tannin: 35, acidity: 60, aroma: 78),
                       varietyHints: ["v_velrune", "v_helvar_sauvage"],
                       blurb: "Aromatically intense, recipe whispered by an apothecary."),
        BlendingRecipe(id: "r_legend_solera", name: "Legend's Solera",
                       target: TasteProfile(body: 64, tannin: 55, acidity: 60, aroma: 68),
                       varietyHints: ["v_aurelan_noir", "v_carmene_carrare", "v_tasselino"],
                       blurb: "Domain legend, solera-style fractional blend.")
    ]

    static func recipe(_ id: String) -> BlendingRecipe? {
        recipes.first(where: { $0.id == id })
    }

    // MARK: - 30 Achievements

    static let achievements: [Achievement] = [
        Achievement(id: "a_first_harvest", title: "First Harvest", blurb: "Bring in fruit for the first time."),
        Achievement(id: "a_first_press", title: "First Press", blurb: "Send harvested fruit to the press."),
        Achievement(id: "a_first_barrel", title: "First Barrel", blurb: "Begin aging a wine in oak or steel."),
        Achievement(id: "a_first_bottle", title: "First Bottling", blurb: "Bottle a finished wine."),
        Achievement(id: "a_first_sale", title: "First Sale", blurb: "Complete a buyer order."),
        Achievement(id: "a_ten_year_age", title: "Decade in the Cellar", blurb: "Age a wine ten consecutive years."),
        Achievement(id: "a_medal_bronze", title: "Bronze Medal", blurb: "Earn a bronze medal at any tasting."),
        Achievement(id: "a_medal_silver", title: "Silver Medal", blurb: "Earn a silver medal at any tasting."),
        Achievement(id: "a_medal_gold", title: "Gold Medal", blurb: "Earn a gold medal at any tasting."),
        Achievement(id: "a_all_varieties", title: "Twelve Varieties", blurb: "Plant all twelve grape varieties at least once."),
        Achievement(id: "a_all_terroirs", title: "Five Terroirs", blurb: "Plant in all five terroirs."),
        Achievement(id: "a_all_barrels", title: "Eight Barrels", blurb: "Use all eight barrel types at least once."),
        Achievement(id: "a_hundred_buyers", title: "Hundred Buyers", blurb: "Complete one hundred buyer orders."),
        Achievement(id: "a_signature", title: "Signature Cuvee", blurb: "Discover a blending recipe by accident."),
        Achievement(id: "a_grand_cru", title: "Grand Cru", blurb: "Earn a perfect score at a tasting event."),
        Achievement(id: "a_estate_rich", title: "Five Thousand Coins", blurb: "Hold five thousand coins in the treasury."),
        Achievement(id: "a_ten_upgrades", title: "Ten Upgrades", blurb: "Acquire ten estate upgrades."),
        Achievement(id: "a_survive_fire", title: "After the Smoke", blurb: "Survive a wildfire event without bankruptcy."),
        Achievement(id: "a_survive_mildew", title: "Cleared the Vines", blurb: "Treat a mildew outbreak successfully."),
        Achievement(id: "a_royal_seal", title: "Royal Seal", blurb: "Complete a Royal Sommelier order."),
        Achievement(id: "a_critic_praise", title: "Critic's Praise", blurb: "Complete a Wine Critic order."),
        Achievement(id: "a_summer_court", title: "Summer Court Favor", blurb: "Complete a Summer Court order."),
        Achievement(id: "a_winter_court", title: "Winter Court Favor", blurb: "Complete a Winter Court order."),
        Achievement(id: "a_twenty_lots", title: "Twenty Bottled Lots", blurb: "Bottle twenty distinct lots."),
        Achievement(id: "a_full_cellar", title: "Full Cellar", blurb: "Maintain ten active barrels simultaneously."),
        Achievement(id: "a_quarter_century", title: "Quarter Century", blurb: "Reach the twenty-fifth year of mastery."),
        Achievement(id: "a_master_tier", title: "Master Valley", blurb: "Reach the Master prestige tier."),
        Achievement(id: "a_legendary_tier", title: "Legendary Domaine", blurb: "Reach the Legendary Domaine prestige tier."),
        Achievement(id: "a_recipe_explorer", title: "Recipe Explorer", blurb: "Unlock ten distinct blending recipes."),
        Achievement(id: "a_diversified", title: "Diversified Plantings", blurb: "Hold six plots of different varieties at once.")
    ]

    static func achievement(_ id: String) -> Achievement? {
        achievements.first(where: { $0.id == id })
    }

    // MARK: - 8 Annual Tasting Events

    static let tastings: [TastingEvent] = [
        TastingEvent(
            id: "te_capital_grand",
            name: "Capital Grand Tasting",
            blurb: "The premier tasting of the realm. Judges from across the duchies.",
            judges: [
                TastingJudge(name: "Lady Vermillion", preference: TasteProfile(body: 70, tannin: 60, acidity: 55, aroma: 65)),
                TastingJudge(name: "Master Aldebar", preference: TasteProfile(body: 65, tannin: 55, acidity: 60, aroma: 70)),
                TastingJudge(name: "Prince Tasselot", preference: TasteProfile(body: 60, tannin: 50, acidity: 60, aroma: 68)),
                TastingJudge(name: "Sister Verena", preference: TasteProfile(body: 60, tannin: 50, acidity: 60, aroma: 60)),
                TastingJudge(name: "Viceroy Tellan", preference: TasteProfile(body: 65, tannin: 55, acidity: 55, aroma: 65))
            ]),
        TastingEvent(
            id: "te_river_cup",
            name: "River Valley Cup",
            blurb: "Wines of the river-bench estates compete for the silver carafe.",
            judges: [
                TastingJudge(name: "Bargemaster Quill", preference: TasteProfile(body: 55, tannin: 40, acidity: 60, aroma: 60)),
                TastingJudge(name: "Innkeeper Mara", preference: TasteProfile(body: 50, tannin: 35, acidity: 60, aroma: 55)),
                TastingJudge(name: "Father Orin", preference: TasteProfile(body: 55, tannin: 40, acidity: 55, aroma: 60)),
                TastingJudge(name: "Captain Reeve", preference: TasteProfile(body: 60, tannin: 45, acidity: 50, aroma: 55)),
                TastingJudge(name: "Madam Estral", preference: TasteProfile(body: 55, tannin: 40, acidity: 60, aroma: 65))
            ]),
        TastingEvent(
            id: "te_mountain_flight",
            name: "Mountain Flight Contest",
            blurb: "Cold-climate aromatic whites and high-altitude reds.",
            judges: [
                TastingJudge(name: "Alpinist Yvet", preference: TasteProfile(body: 36, tannin: 8, acidity: 75, aroma: 75)),
                TastingJudge(name: "Hunter Brink", preference: TasteProfile(body: 55, tannin: 45, acidity: 65, aroma: 65)),
                TastingJudge(name: "Cartographer Hael", preference: TasteProfile(body: 45, tannin: 25, acidity: 70, aroma: 70)),
                TastingJudge(name: "Magister Vossen", preference: TasteProfile(body: 50, tannin: 35, acidity: 65, aroma: 70)),
                TastingJudge(name: "Songsmith Wend", preference: TasteProfile(body: 40, tannin: 15, acidity: 70, aroma: 78))
            ]),
        TastingEvent(
            id: "te_coastal_open",
            name: "Coastal Open",
            blurb: "Salt-air judges favor crisp whites and supple coastal reds.",
            judges: [
                TastingJudge(name: "Harbormaster Lir", preference: TasteProfile(body: 40, tannin: 15, acidity: 70, aroma: 65)),
                TastingJudge(name: "Captain Selna", preference: TasteProfile(body: 50, tannin: 40, acidity: 60, aroma: 60)),
                TastingJudge(name: "Doctor Maris", preference: TasteProfile(body: 38, tannin: 10, acidity: 75, aroma: 70)),
                TastingJudge(name: "Cook Tarrin", preference: TasteProfile(body: 50, tannin: 35, acidity: 65, aroma: 60)),
                TastingJudge(name: "Trader Iola", preference: TasteProfile(body: 45, tannin: 20, acidity: 70, aroma: 65))
            ]),
        TastingEvent(
            id: "te_harvest_fair",
            name: "Harvest Fair Showcase",
            blurb: "Crowd-pleasers and approachable reds win the fair's ribbon.",
            judges: [
                TastingJudge(name: "Baker Renn", preference: TasteProfile(body: 50, tannin: 35, acidity: 55, aroma: 55)),
                TastingJudge(name: "Carter Brel", preference: TasteProfile(body: 55, tannin: 40, acidity: 55, aroma: 50)),
                TastingJudge(name: "Smith Adlin", preference: TasteProfile(body: 60, tannin: 45, acidity: 50, aroma: 50)),
                TastingJudge(name: "Weaver Onna", preference: TasteProfile(body: 45, tannin: 30, acidity: 60, aroma: 55)),
                TastingJudge(name: "Steward Pol", preference: TasteProfile(body: 50, tannin: 35, acidity: 55, aroma: 55))
            ]),
        TastingEvent(
            id: "te_critics_judgment",
            name: "Critics' Judgment",
            blurb: "Hardened palates require precision and elegance.",
            judges: [
                TastingJudge(name: "Critic Velia", preference: TasteProfile(body: 60, tannin: 55, acidity: 65, aroma: 75)),
                TastingJudge(name: "Editor Halbert", preference: TasteProfile(body: 65, tannin: 60, acidity: 60, aroma: 70)),
                TastingJudge(name: "Author Wenley", preference: TasteProfile(body: 60, tannin: 55, acidity: 65, aroma: 75)),
                TastingJudge(name: "Scribe Ardin", preference: TasteProfile(body: 60, tannin: 55, acidity: 60, aroma: 70)),
                TastingJudge(name: "Reviewer Pell", preference: TasteProfile(body: 60, tannin: 50, acidity: 65, aroma: 75))
            ]),
        TastingEvent(
            id: "te_old_valleys",
            name: "Old Valleys' Convocation",
            blurb: "Library bottles only. The eldest vines speak through them.",
            judges: [
                TastingJudge(name: "Grand Master Olen", preference: TasteProfile(body: 65, tannin: 60, acidity: 55, aroma: 65)),
                TastingJudge(name: "Cooper Veren", preference: TasteProfile(body: 60, tannin: 55, acidity: 55, aroma: 60)),
                TastingJudge(name: "Patriarch Sallin", preference: TasteProfile(body: 70, tannin: 60, acidity: 55, aroma: 60)),
                TastingJudge(name: "Cellarmaster Yew", preference: TasteProfile(body: 65, tannin: 55, acidity: 55, aroma: 65)),
                TastingJudge(name: "Master Pelham", preference: TasteProfile(body: 65, tannin: 60, acidity: 55, aroma: 70))
            ]),
        TastingEvent(
            id: "te_summer_pavilion",
            name: "Summer Pavilion",
            blurb: "Bright, refreshing whites and rosés dominate the pavilion's tables.",
            judges: [
                TastingJudge(name: "Duchess Liriel", preference: TasteProfile(body: 40, tannin: 15, acidity: 70, aroma: 70)),
                TastingJudge(name: "Court Painter Aen", preference: TasteProfile(body: 45, tannin: 20, acidity: 65, aroma: 75)),
                TastingJudge(name: "Aviary Keeper Norn", preference: TasteProfile(body: 38, tannin: 10, acidity: 70, aroma: 75)),
                TastingJudge(name: "Garden Master Bern", preference: TasteProfile(body: 42, tannin: 18, acidity: 68, aroma: 70)),
                TastingJudge(name: "Steward Maren", preference: TasteProfile(body: 45, tannin: 20, acidity: 65, aroma: 70))
            ])
    ]

    static func tasting(_ id: String) -> TastingEvent? {
        tastings.first(where: { $0.id == id })
    }

    // MARK: - 6 Prestige Tiers

    static let prestigeTiers: [PrestigeTier] = [
        PrestigeTier(id: "pt_apprentice", name: "Apprentice", medalsRequired: 0, revenueRequired: 0,
                     blurb: "The first lights in the cellar lantern."),
        PrestigeTier(id: "pt_master", name: "Master", medalsRequired: 2, revenueRequired: 2000,
                     blurb: "Trusted by neighboring estates."),
        PrestigeTier(id: "pt_estate_lord", name: "Estate Lord", medalsRequired: 5, revenueRequired: 6000,
                     blurb: "Acknowledged at the county tables."),
        PrestigeTier(id: "pt_region_reference", name: "Region Reference", medalsRequired: 10, revenueRequired: 14000,
                     blurb: "Your bottles set the regional standard."),
        PrestigeTier(id: "pt_national_brand", name: "National Brand", medalsRequired: 16, revenueRequired: 28000,
                     blurb: "Crown commission, distant tastings, your label spreads."),
        PrestigeTier(id: "pt_legendary", name: "Legendary Domaine", medalsRequired: 24, revenueRequired: 48000,
                     blurb: "Whispered about in cellars across the continent.")
    ]

    static func prestigeTier(forMedals medals: Int, revenue: Int) -> PrestigeTier {
        var current = prestigeTiers[0]
        for tier in prestigeTiers {
            if medals >= tier.medalsRequired && revenue >= tier.revenueRequired {
                current = tier
            }
        }
        return current
    }
}
